config/routes.rb
Rails.application.routes.draw do
  resources :help_mes, only: [:index] do
    patch "resolve"
    patch "claim"
  end
  post "update_table", to: "help_mes#update_table"

end

app/models/help_me.rb
class HelpMe < ActiveRecord::Base

<<<<<<< HEAD
  def self.latest_help_mes(min_updated_at = nil)
    if min_updated_at
      where_line = "updated_at > :min_updated_at"
      where_options = { min_updated_at: min_updated_at }
      @help_mes = HelpMe.where(where_line, where_args)
    else
      @help_mes = HelpMe.all
    end

    @help_mes = @help_mes.where("resolved")

    @help_mes
  end

=======
>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d
  def resolve!
    self.update!(resolved: true)
  end

  def claim!
    self.update!(claimed: true)
  end

  def help_type
    if content[0] == "q"
      "Question"
    elsif content[0] == "r"
      "Review request"
    else
<<<<<<< HEAD
=======
      # content
      #(content.split(//) - desk_number.to_s.split(//)).join.first.upcase
>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d
      content.match(/[a-zA-Z]+/).to_s
    end
  end

  def desk_number     #icky
    content.match(/\d{1,2}[ab]?/).to_s
  end

  def est_hour
    (timing[-13..-12].to_i - 4) % 24
  end

<<<<<<< HEAD
=======
  # def nice_mins
  #   timing.min.to_s.rjust(2, '0')
  # end

>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d
  def to_s
    "#{help_type} at Desk #{desk_number} by #{author} at #{timing[-13..-12]}:#{timing[-10..-9]}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


end

app/controllers/help_mes_controller.rb
class HelpMesController < ApplicationController
  helper_method :update_table

<<<<<<< HEAD
  def update_table(token = "a691fc881e4d73852291991d9b7973",
                    room_id = 865319)
=======
  def update_table(token = "#{YOUR TOKEN YOU MUST ENTER IT}",
                    room_id = "{YOUR ROOM ID I HAVE A SCRIPT FOR THIS}")
>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d

    hipchat_api = HipChat::API.new(token)
    recent_msgs = hipchat_api.rooms_history(room_id, "recent", "EST")["messages"]

    recent_msgs.each do |msg|
      if HelpMe.find_by_timing(msg["date"]).nil?   #eh it works (maybe)
        if ( msg["message"] =~ /[a-zA-Z]+\s?\d{1,2}[ab]?$/ )
          HelpMe.create!(author: msg["from"]["name"],
                        content: msg["message"].match(/[a-zA-Z]+\s?\d{1,2}[ab]?$/).to_s,
                        timing: msg["date"])
        end
      end
    end

    redirect_to help_mes_url
  end

  def resolve
    @help_me = HelpMe.find(params[:help_me_id])
    if @help_me
      @help_me.resolve!
    end
    redirect_to help_mes_url
  end

  def claim
    @help_me = HelpMe.find(params[:help_me_id])
    if @help_me
      @help_me.claim!
    end
    redirect_to help_mes_url
  end

  def index
<<<<<<< HEAD

    if params[:min_updated_at]
      @help_mes = HelpMe.latest_help_mes(params[:min_updated_at])
      puts "knew there was a min"
    else
      puts "did not even know"
      @help_mes = HelpMe.latest_help_mes() #probably not what we ultimately want
    end

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @help_mes}
    end
=======
    @help_mes = HelpMe.all
    render :index
>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/help_mes/index.html.erb
<h1>Panicking Students</h1>

<<<<<<< HEAD
<table class="panicks">

    <tr>
      <td>
        <button class="update-dat">new updatin</button>
  <!-- that su- the silliest thing we have done all day -->
      </td>
    </tr>

=======
<table>
>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d
<% HelpMe.all.each do |halp| %>
  <% next if halp.resolved %>
  <tr>
    <td>
      <form action="<%= help_me_resolve_url(halp.id) %>"
            method="post">
        <input type="hidden" value="PATCH" name="_method">
        <input type="submit" value="Resolve">
      </form>
    </td>
    <td>
    <% if halp.claimed %>
      CLAIMED
    <% else %>
      <form action="<%= help_me_claim_url(halp.id) %>"
            method="post">
        <input type="hidden" value="PATCH" name="_method">
        <input type="submit" value="Claim">
      </form>
    <% end %>
    </td>
    <td>
      <%= halp %>
    </td>
  </tr>
<% end %>

</table>

<form action="<%= update_table_url %>"
      method="post">
  <input id="updatin" type="submit" value="Update">
</form>

<<<<<<< HEAD


<script>
  //setInterval(function () {document.getElementById("updatin").click();}, 10000);
</script>
=======
<script>setInterval(function () {document.getElementById("updatin").click();}, 10000)</script>
>>>>>>> 626042beb73e6be794861cb6a5f90d04b8bbcf8d

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Halpin</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

<%= yield %>

</body>
</html>